#!/usr/bin/env bash
# Emits a markdown table of an APK's total size and per-ABI native library
# sizes to $GITHUB_STEP_SUMMARY (falls back to stdout when that variable is
# unset, e.g. for local runs).
#
# Usage:
#   ./scripts/report-apk-sizes.sh <path-to-apk>

set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 <path-to-apk>" >&2
  exit 2
fi

apk_path="$1"
apk_name="$(basename "$apk_path")"

if [[ ! -f "$apk_path" ]]; then
  echo "::error::APK not found at $apk_path" >&2
  exit 1
fi

out="${GITHUB_STEP_SUMMARY:-/dev/stdout}"

total_bytes=$(stat -c%s "$apk_path" 2>/dev/null || stat -f%z "$apk_path")
total_human=$(numfmt --to=iec --suffix=B "$total_bytes" 2>/dev/null || echo "${total_bytes} bytes")

{
  echo "## APK size report — $apk_name"
  echo
  echo "| Metric | Value |"
  echo "|---|---|"
  echo "| Total APK size | ${total_human} (${total_bytes} bytes) |"
  echo
  echo "### Native libraries (\`lib/**\`)"
  echo
  echo "| ABI | Library | Size |"
  echo "|---|---|---|"
} >> "$out"

# unzip -l columns: length, date, time, name
unzip -l "$apk_path" | awk '$4 ~ /^lib\// {print $1, $4}' | while read -r size path; do
  abi="$(echo "$path" | cut -d/ -f2)"
  libname="$(basename "$path")"
  human=$(numfmt --to=iec --suffix=B "$size" 2>/dev/null || echo "${size} bytes")
  echo "| $abi | $libname | $human |" >> "$out"
done

echo >> "$out"
echo "_Generated by scripts/report-apk-sizes.sh_" >> "$out"

echo "==> Size report written to ${GITHUB_STEP_SUMMARY:-stdout}"
